### PR TITLE
Reimplement certificate controller

### LINKED ISSUE #356: Don't retry if rate-limited by LE
count: 1
firstTimestamp: 2017-08-09T03:58:52Z
involvedObject:
  apiVersion: voyager.appscode.com/v1beta1
  kind: Certificate
  name: domain-dns
  namespace: default
  resourceVersion: "35789603"
  uid: 913353da-7770-11e7-bbc1-42010a800002
lastTimestamp: 2017-08-09T03:58:52Z
message: "Failed to renew certificate, Reason \nCaused By:\nacme: Error 429 - urn:acme:error:rateLimited
  - Error creating new cert :: too many certificates already issued for exact set
  of domains: api.appscode.info,auth.appscode.info,composer.appscode.info,cowrypay-api.appscode.info,docker.appscode.info,jenkins.appscode.info,maven.appscode.info,npm.appscode.info,qacode.appscode.ninja,tiller-2.appscode.info\nStack
  trace:\n/go/src/github.com/appscode/voyager/pkg/certificate/controller.go:172                     (*Controller).Process\n/go/src/github.com/appscode/voyager/pkg/operator/certificate_tprs.go:41
  \                  (*Operator).WatchCertificateTPRs.func3\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:192
  ResourceEventHandlerFuncs.OnAdd\n<autogenerated>:54                                                                        (*ResourceEventHandlerFuncs).OnAdd\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:270
  NewInformer.func1\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
  (*DeltaFIFO).Pop\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:147
  (*controller).processLoop\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
  processLoop)-fm\n/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
  \  JitterUntil.func1\n/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
  \  JitterUntil\n/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
  \  Until\n/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
  (*controller).Run\n/go/src/github.com/appscode/voyager/pkg/operator/certificate_tprs.go:74
  \                  (*Operator).WatchCertificateTPRs\n/usr/local/go/src/runtime/asm_amd64.s:2197
  \                                               goexit"
metadata:
  creationTimestamp: 2017-08-09T03:58:52Z
  name: domain-dns.14d911720f465c63
  namespace: default
  resourceVersion: "17383790"
  selfLink: /api/v1/namespaces/default/events/domain-dns.14d911720f465c63
  uid: 0ed4e9ba-7cb7-11e7-bbc1-42010a800002
reason: RenewFailed
source:
  component: Voyager operator
type: Warning

### LINKED ISSUE #366: Don't require spec.providerCredentialSecretName for own provider
When Voyager is used in AWS, it should be possible to skip the extra secret. User should be able to just use the existing IAM permissions directly (like we do for opening firewall).

Same goes for GCE, etc.

ref: #337

### LINKED ISSUE #370: ProviderCredential has to be created before Certificate object
Retry after 60 secs for a total of 5 tries.

### LINKED ISSUE #382: Avoid concurrency for NewACMEClient
aws.NewSession() does not allow concurrent writers.

os.Setenv("AWS_SDK_LOAD_CONFIG", "true")

### LINKED ISSUE #393: Validate certificates
- `voyager` should check on start and in `check` command.

### LINKED ISSUE #505: Redesign Certificate CRD
```
spec:
  acmeUserSecretName:
  chanlleger:
	http:
	  ingress: {}
	dns:
	  cloud: gce
	  credentialSec
  storage:
    secret:
      name:
    vault:
      name:
      prefix: prod-cluster
```
Status:
https://github.com/kubernetes/api/blob/e24ed681f56165befbea50a24f7e9f1c079ac366/certificates/v1beta1/types.go#L83

### LINKED ISSUE #526: AWS secrets don't seem to be used for ACME validation
I'm trying to get voyager to get a certificate from let's encrypt.  I've created a secret containing AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY and I've created a voyager certificate TPR referencing that secret.

The voyager operator logs show it failing to make the call to route 53, and the error message indicates it is using the identity provided to the EC2 host the pod is running on, rather than the expected identity associated with the access key mentioned above.

```
I0922 22:03:44.692800       1 controller.go:225] trying to retrive acmeUser data
I0922 22:03:44.696485       1 controller.go:252] ACMEUserInfo data found is secretacme-jenkins2-cert
I0922 22:03:44.764078       1 logs.go:19] [INFO][jenkins2.x.io] acme: Obtaining bundled SAN certificate
I0922 22:03:45.309837       1 logs.go:19] [INFO][jenkins2.x.io] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/xxx...
I0922 22:03:45.309869       1 logs.go:19] [INFO][jenkins2.x.io] acme: Could not find solver for: tls-sni-01
I0922 22:03:45.309877       1 logs.go:19] [INFO][jenkins2.x.io] acme: Could not find solver for: http-01
I0922 22:03:45.309884       1 logs.go:19] [INFO][jenkins2.x.io] acme: Trying to solve DNS-01
I0922 22:03:45.685164       1 controller.go:183] Error occurred for jenkins2.x.io, reason Error presenting token: Failed to determine Route 53 hosted zone ID: AccessDenied: User: arn:aws:sts::111111111111:assumed-role/kube24-Nodepool1-U5VAGNWC1MHX-IAMRoleWorker-EG19YHC6EJ7S/i-01d5e28d360712cfc is not authorized to perform: route53:ListHostedZonesByName
        status code: 403, request id: e72fd92f-9fe1-11e7-a9be-2bd1577fb68c
```

### PR DESCRIPTION
**Pull request by sadlil**
Fixes #505
Fixes #370
Fixes #382
Fixes #526 
Fixes #366 
Fixes #393 
Fixes #356

### CODE REVIEW

**Comment by tamalsaha** [comment]
- [ ] Fix RBACs.

File: apis/voyager/ingress.go [hunk 1]
```diff
@@ -107,6 +107,9 @@ type IngressTLS struct {
 	// by an IngressRule, the SNI host is used for termination and value of the
 	// Host header is used for routing.
 	SecretName string `json:"secretName,omitempty"`
+
+	// Certificate name to used tls termination. Will be ignored if secret name specified.
+	Certificate apiv1.ObjectReference `json:"certificate,omitempty"`
```
Comment (tamalsaha) [inline apis/voyager/ingress.go]: `Certificate *apiv1.ObjectReference`

Should this be a pointer?

**Comment by tamalsaha** [comment]
What purpose does 
```
	CertURL       string      `json:"certURL"`
	CertStableURL string      `json:"certStableURL"`
	AccountRef    string      `json:"accountRef,omitempty"`
```
fields serve?

File: pkg/ingress/rbac.go [hunk 2]
```diff
@@ -70,14 +81,14 @@ func (c *controller) ensureRoles() error {
...
 			Resources:     []string{"ingresses"},
 			ResourceNames: []string{c.Ingress.Name},
-			Verbs:         []string{"get"},
+			Verbs:         []string{"get", "list", "watch"},
 		})
 	case api_v1beta1.APISchemaIngress:
 		defaultRole.Rules = append(defaultRole.Rules, rbac.PolicyRule{
 			APIGroups:     []string{extensions.GroupName},
 			Resources:     []string{"ingresses"},
 			ResourceNames: []string{c.Ingress.Name},
```
Comment (tamalsaha) [inline pkg/ingress/rbac.go]: Can you define ResourceName and watch Ingress at the same time?
